
export const Knockdown_State_Static =
{
    0: "Neutral",
    1: "Walking",
    2: "Rising to Normal Jump",
    3: "Normal Jump",
    4: "Landing from Jump",
    5: "Starting to Crouch",
    6: "Fully-Crouched",
    7: "Rising from Crouch",
    8: "Turning Around",
    9: "Crouch Turning Around",
    10: "Forward Dashing",
    11: "Back Dashing",
    12: "???",
    13: "Rising to Super Jump",
    14: "Super Jumping",
    15: "Air Recovery",
    16: "???",
    17: "Getting up from OTG Stun & Tech Roll",
    18: "Blocking",
    19: "Air-Prox-Block & Blocking & Pushblocking",
    20: "Normal Attacks",
    21: "Special Attacks",
    22: "Assist value after match ends",
    23: "Extra OTG Stun",
    24: "Flight Neutral",
    25: "Corner Jump",
    26: "Air Dash",
    27: "Tech Hit flip out",
    28: "Tag/Assist-is-Called",
    29: "Supers & Snapbacks & THC",
    30: "Throwing opponent",
    31: "Being thrown",
    32: "Stunned & Forced-OTG Stun",
    33: "???",
    34: "OC Launcher",
};
export const Prox_Block_Static =
{
    0:	"Neutral",
    1:	"Air",
    2:	"Dashing",
    3:	"Crouching",
    4:	"Turning Around",
    5:	"Ground Block",
    6:	"Air Block",
    7:	"Standing Punches",
    8:	"Standing Kicks",
    9:	"Crouching Punches",
    10:	"Crouching Kicks",
    11:	"Air Punches",
    12:	"Air Kicks",
    13:	"Stunned",
    14:	"???",
    15:	"Throwing",
    16:	"Being thrown",
    17:	"Getting up from OTG (Invulnerable,",
    18:	"Match Start (Throw Invulnerable,",
    19:	"Win Pose",
    20:	"Tag-in & OC Launcher",
    21:	"Specials & Snapbacks",
    22:	"Supers",
    23:	"???",
    24:	"Assist Related",
    25:	"???",
    26:	"Air Dash",
}

export const namesTable_Static =
{
    0: "Ryu",
    1: "Zangief",
    2: "Guile",
    3: "Morrigan",
    4: "Anakaris",
    5: "Strider Hiryu",
    6: "Cyclops",
    7: "Wolverine (Adamantium)",
    8: "Psylocke",
    9: "Iceman",
    10: "Rogue",
    11: "Captain America",
    12: "Spider-Man",
    13: "Hulk",
    14: "Venom",
    15: "Doctor Doom",
    16: "Tron Bonne",
    17: "Jill",
    18: "Hayato",
    19: "Ruby Heart",
    20: "Sonson",
    21: "Amingo",
    22: "Marrow",
    23: "Cable",
    24: "Abyss-1",
    25: "Abyss-2",
    26: "Abyss-3",
    27: "Chun-Li",
    28: "Megaman",
    29: "Roll",
    30: "Akuma",
    31: "B.B. Hood",
    32: "Felicia",
    33: "Charlie",
    34: "Sakura",
    35: "Dan",
    36: "Cammy",
    37: "Dhalsim",
    38: "M.Bison",
    39: "Ken",
    40: "Gambit",
    41: "Juggernaut",
    42: "Storm",
    43: "Sabretooth",
    44: "Magneto",
    45: "Shuma-Gorath",
    46: "War Machine",
    47: "Silver Samurai",
    48: "Omega Red",
    49: "Spiral",
    50: "Colossus",
    51: "Iron Man",
    52: "Sentinel",
    53: "Blackheart",
    54: "Thanos",
    55: "Jin",
    56: "Captain Commando",
    57: "Wolverine (Bone)",
    58: "Servbot",
}

// export const StagesTable_Static =
// {
// 	0	: "Boat1",
// 	1	: "Desert1",
// 	2	: "Factory",
// 	3	: "Carnival1",
// 	4	: "Bridge1",
// 	5	: "Cave2",
// 	6	: "Clock2",
// 	7	: "Raft2",
// 	8	: "Abyss",
// 	9	: "Boat2",
// 	10	: "Desert2",
// 	11	: "Training",
// 	12	: "Carnival2",
// 	13	: "Bridge2",
// 	14	: "Cave1",
// 	15	: "Clock1",
// 	16	: "Raft1"
// }
