export const Knockdown_State_Static =
{
  0: "Neutral",
  1: "Walking",
  2: "Rising to Normal Jump",
  3: "Normal Jump",
  4: "Landing from Jump",
  5: "Starting to Crouch",
  6: "Fully-Crouched",
  7: "Rising from Crouch",
  8: "Turning Around",
  9: "Crouch Turning Around",
  10: "Forward Dashing",
  11: "Back Dashing",
  12: "???",
  13: "Rising to Super Jump",
  14: "Super Jumping",
  15: "Air Recovery",
  16: "???",
  17: "Getting up from OTG Stun & Tech Roll",
  18: "Blocking",
  19: "Air-Prox-Block & Blocking & Pushblocking",
  20: "Normal Attacks",
  21: "Special Attacks",
  22: "Assist value after match ends",
  23: "Extra OTG Stun",
  24: "Flight Neutral",
  25: "Corner Jump",
  26: "Air Dash",
  27: "Tech Hit flip out",
  28: "Tag/Assist-is-Called",
  29: "Supers & Snapbacks & THC",
  30: "Throwing opponent",
  31: "Being thrown",
  32: "Stunned & Forced-OTG Stun",
  33: "???",
  34: "OC Launcher",
};
export const Prox_Block_Static =
{
  0: "Neutral",
  1: "Air",
  2: "Dashing",
  3: "Crouching",
  4: "Turning Around",
  5: "Ground Block",
  6: "Air Block",
  7: "Standing Punches",
  8: "Standing Kicks",
  9: "Crouching Punches",
  10: "Crouching Kicks",
  11: "Air Punches",
  12: "Air Kicks",
  13: "Stunned",
  14: "???",
  15: "Throwing",
  16: "Being thrown",
  17: "Getting up from OTG (Invulnerable),",
  18: "Match Start (Throw Invulnerable,",
  19: "Win Pose",
  20: "Tag-in & OC Launcher",
  21: "Specials & Snapbacks",
  22: "Supers",
  23: "???",
  24: "Assist Related",
  25: "???",
  26: "Air Dash",
};

export const namesTable_Static =
{
  0: "Ryu",
  1: "Zangief",
  2: "Guile",
  3: "Morrigan",
  4: "Anakaris",
  5: "Strider Hiryu",
  6: "Cyclops",
  7: "Wolverine (Adamantium)",
  8: "Psylocke",
  9: "Iceman",
  10: "Rogue",
  11: "Captain America",
  12: "Spider-Man",
  13: "Hulk",
  14: "Venom",
  15: "Doctor Doom",
  16: "Tron Bonne",
  17: "Jill",
  18: "Hayato",
  19: "Ruby Heart",
  20: "Sonson",
  21: "Amingo",
  22: "Marrow",
  23: "Cable",
  24: "Abyss-1",
  25: "Abyss-2",
  26: "Abyss-3",
  27: "Chun-Li",
  28: "Megaman",
  29: "Roll",
  30: "Akuma",
  31: "B.B. Hood",
  32: "Felicia",
  33: "Charlie",
  34: "Sakura",
  35: "Dan",
  36: "Cammy",
  37: "Dhalsim",
  38: "M.Bison",
  39: "Ken",
  40: "Gambit",
  41: "Juggernaut",
  42: "Storm",
  43: "Sabretooth",
  44: "Magneto",
  45: "Shuma-Gorath",
  46: "War Machine",
  47: "Silver Samurai",
  48: "Omega Red",
  49: "Spiral",
  50: "Colossus",
  51: "Iron Man",
  52: "Sentinel",
  53: "Blackheart",
  54: "Thanos",
  55: "Jin",
  56: "Captain Commando",
  57: "Wolverine (Bone)",
  58: "Servbot",
};

export var floatingPointAddresses =
  [
    'X_Gravity',
    'X_Position_Arena',
    'X_Position_From_Enemy',
    'X_Position_Screen',
    'Y_Gravity',
    'Y_Position_Arena',
    'Y_Position_From_Enemy',
    'Y_Position_Screen',
    'Y_Velocity',
  ];
export var MinMaxList =
  [
    'P1_A_X_Gravity',
    'P1_A_X_Position_Arena',
    'P1_A_X_Position_From_Enemy',
    'P1_A_X_Position_Screen',
    'P1_A_Y_Gravity',
    'P1_A_Y_Position_Arena',
    'P1_A_Y_Position_From_Enemy',
    'P1_A_Y_Position_Screen',
    'P1_A_Y_Velocity',
    'P1_B_X_Gravity',
    'P1_B_X_Position_Arena',
    'P1_B_X_Position_From_Enemy',
    'P1_B_X_Position_Screen',
    'P1_B_Y_Gravity',
    'P1_B_Y_Position_Arena',
    'P1_B_Y_Position_From_Enemy',
    'P1_B_Y_Position_Screen',
    'P1_B_Y_Velocity',
    'P1_C_X_Gravity',
    'P1_C_X_Position_Arena',
    'P1_C_X_Position_From_Enemy',
    'P1_C_X_Position_Screen',
    'P1_C_Y_Gravity',
    'P1_C_Y_Position_Arena',
    'P1_C_Y_Position_From_Enemy',
    'P1_C_Y_Position_Screen',
    'P1_C_Y_Velocity',
    'P2_A_X_Gravity',
    'P2_A_X_Position_Arena',
    'P2_A_X_Position_From_Enemy',
    'P2_A_X_Position_Screen',
    'P2_A_Y_Gravity',
    'P2_A_Y_Position_Arena',
    'P2_A_Y_Position_From_Enemy',
    'P2_A_Y_Position_Screen',
    'P2_A_Y_Velocity',
    'P2_B_X_Gravity',
    'P2_B_X_Position_Arena',
    'P2_B_X_Position_From_Enemy',
    'P2_B_X_Position_Screen',
    'P2_B_Y_Gravity',
    'P2_B_Y_Position_Arena',
    'P2_B_Y_Position_From_Enemy',
    'P2_B_Y_Position_Screen',
    'P2_B_Y_Velocity',
    'P2_C_X_Gravity',
    'P2_C_X_Position_Arena',
    'P2_C_X_Position_From_Enemy',
    'P2_C_X_Position_Screen',
    'P2_C_Y_Gravity',
    'P2_C_Y_Position_Arena',
    'P2_C_Y_Position_From_Enemy',
    'P2_C_Y_Position_Screen',
    'P2_C_Y_Velocity',
    'P1_A_Bison_214kk_Timer',
    'P1_A_Dhalsim_214kk_Timer',
    'P1_A_Doom_214kk_Timer',
    'P1_A_Iron_Man_214kk_Timer',
    'P1_A_Magneto_214kk_Timer',
    'P1_A_Megaman_214kk_Timer',
    'P1_A_Sentinel_214kk_Timer',
    'P1_A_Storm_214kk_Timer',
    'P1_A_War_Machine_214kk_Timer',
    'P1_B_Bison_214kk_Timer',
    'P1_B_Dhalsim_214kk_Timer',
    'P1_B_Doom_214kk_Timer',
    'P1_B_Iron_Man_214kk_Timer',
    'P1_B_Magneto_214kk_Timer',
    'P1_B_Megaman_214kk_Timer',
    'P1_B_Sentinel_214kk_Timer',
    'P1_B_Storm_214kk_Timer',
    'P1_B_War_Machine_214kk_Timer',
    'P1_C_Bison_214kk_Timer',
    'P1_C_Dhalsim_214kk_Timer',
    'P1_C_Doom_214kk_Timer',
    'P1_C_Iron_Man_214kk_Timer',
    'P1_C_Magneto_214kk_Timer',
    'P1_C_Megaman_214kk_Timer',
    'P1_C_Sentinel_214kk_Timer',
    'P1_C_Storm_214kk_Timer',
    'P1_C_War_Machine_214kk_Timer',
    'P2_A_Bison_214kk_Timer',
    'P2_A_Dhalsim_214kk_Timer',
    'P2_A_Doom_214kk_Timer',
    'P2_A_Iron_Man_214kk_Timer',
    'P2_A_Magneto_214kk_Timer',
    'P2_A_Megaman_214kk_Timer',
    'P2_A_Sentinel_214kk_Timer',
    'P2_A_Storm_214kk_Timer',
    'P2_A_War_Machine_214kk_Timer',
    'P2_B_Bison_214kk_Timer',
    'P2_B_Dhalsim_214kk_Timer',
    'P2_B_Doom_214kk_Timer',
    'P2_B_Iron_Man_214kk_Timer',
    'P2_B_Magneto_214kk_Timer',
    'P2_B_Megaman_214kk_Timer',
    'P2_B_Sentinel_214kk_Timer',
    'P2_B_Storm_214kk_Timer',
    'P2_B_War_Machine_214kk_Timer',
    'P2_C_Bison_214kk_Timer',
    'P2_C_Dhalsim_214kk_Timer',
    'P2_C_Doom_214kk_Timer',
    'P2_C_Iron_Man_214kk_Timer',
    'P2_C_Magneto_214kk_Timer',
    'P2_C_Megaman_214kk_Timer',
    'P2_C_Sentinel_214kk_Timer',
    'P2_C_Storm_214kk_Timer',
    'P2_C_War_Machine_214kk_Timer',
    'P1_Combo_Meter_Value',
    'P2_Combo_Meter_Value',
  ];
export const miscAddresses =
  [
    'Total_Frames',
    'Camera_Field_of_View',
    'Camera_X_Position',
    'Camera_X_Rotation',
    'Camera_Y_Position',
    'Camera_Y_Rotation',
    'A_2D_Game_Timer',
    'P1_Assist_Flag',
    'P2_Assist_Flag',
    'P1_Attacks_Done',
    'P1_Attacks_Successful',
    'P1_Combo_Meter_Value',
    'P1_Max_Combo',
    'P2_Attacks_Done',
    'P2_Attacks_Successful',
    'P2_Combo_Meter_Value',
    'P2_Max_Combo',
    'P1_Hitbox_Count',
    'P2_Hitbox_Count',
    'P1_Meter_Big',
    'P1_Meter_Small',
    'P2_Meter_Big',
    'P2_Meter_Small',
    'P1_Pause_ID',
    'P2_Pause_ID',
    'Frame_Skip_Counter',
    'Frame_Skip_Cycle_Value',
    'Frame_Skip_Rate',
    'Frame_Skip_Toggle',
    'Is_Paused',
    'Match_Start_Throw_Timer',
    'Match_Tracker',
    'Pause_Count',
    'Stage_Selector',
    'Timer_Secondary',
  ];

export const StagesTable_Static =
{
  0: '142030', //"Boat1",
  1: 'E1540C', //"Desert1",
  2: '6D574F', //"Factory",
  3: 'CF461B', //"Carnival1",
  4: 'ECE4B9', //"Bridge1",
  5: '257B8A', //"Cave2",
  6: 'D0C1AC', //"Clock2",
  7: 'B764AA', //"Raft2",
  8: '263548', //"Abyss",
  9: 'C09A71', //"Boat2",
  10: '3F5FFF', //"Desert2",
  11: '266D04', //"Training",
  12: '74566E', //"Carnival2",
  13: 'E9797F', //"Bridge2",
  14: 'A43812', //"Cave1",
  15: '888885', //"Clock1",
  16: '8CA7DF' //"Raft1"
};