//Names Table
//Decimal Values in the order the the game stores the kvs. For ID_2 value.
//The way the characters are typed has to be consistent throughout 
//the project; any AE change will be predicated on the ID number
const namesTable =
{
	0	: "Ryu",
	1	: "Zangief",
	2	: "Guile",
	3	: "Morrigan",
	4	: "Anakaris",
	5	: "Strider Hiryu",
	6	: "Cyclops",
	7	: "Wolverine (Adamantium)",
	8	: "Psylocke",
	9	: "Iceman",
	10	: "Rogue",
	11	: "Captain America",
	12	: "Spider-Man",
	13	: "Hulk",
	14	: "Venom",
	15	: "Doctor Doom",
	16	: "Tron Bonne",
	17	: "Jill",
	18	: "Hayato",
	19	: "Ruby Heart",
	20	: "Sonson",
	21	: "Amingo",
	22	: "Marrow",
	23	: "Cable",
	24	: "Abyss-1",
	25	: "Abyss-2",
	26	: "Abyss-3",
	27	: "Chun-Li",
	28	: "Megaman",
	29	: "Roll",
	30	: "Akuma",
	31	: "B.B. Hood",
	32	: "Felicia",
	33	: "Charlie",
	34	: "Sakura",
	35	: "Dan",
	36	: "Cammy",
	37	: "Dhalsim",
	38	: "M.Bison",
	39	: "Ken",
	40	: "Gambit",
	41	: "Juggernaut",
	42	: "Storm",
	43	: "Sabretooth",
	44	: "Magneto",
	45	: "Shuma-Gorath",
	46	: "War Machine",
	47	: "Silver Samurai",
	48	: "Omega Red",
	49	: "Spiral",
	50	: "Colossus",
	51	: "Iron Man",
	52	: "Sentinel",
	53	: "Blackheart",
	54	: "Thanos",
	55	: "Jin",
	56	: "Captain Commando",
	57	: "Wolverine (Bone)",
	58	: "Servbot",
}