//Knockdown_State Table
const Knockdown_StateObj =
{
	0	: "Neutral",
	1	: "Walking",
	2	: "Rising to Normal Jump",
	3	: "Normal Jump",
	4	: "Landing from Jump",
	5	: "Starting to Crouch",
	6	: "Fully-Crouched",
	7	: "Rising from Crouch",
	8	: "Turning Around",
	9	: "Crouch Turning Around",
	10	: "Forward Dashing",
	11	: "Back Dashing",
	12	: "???",
	13	: "Rising to Super Jump",
	14	: "Super Jumping",
	15	: "Air Recovery",
	16	: "???",
	17	: "Getting up from OTG Stun & Tech Roll",
	18	: "Blocking",
	19	: "Air-Prox-Block & Blocking & Pushblocking",
	20	: "Normal Attacks",
	21	: "Special Attacks",
	22	: "Assist value after match ends",
	23	: "Extra OTG Stun",
	24	: "Flight Neutral",
	25	: "Corner Jump",
	26	: "Air Dash",
	27	: "Tech Hit flip out",
	28	: "Tag/Assist-is-Called",
	29	: "Supers & Snapbacks & THC",
	30	: "Throwing opponent",
	31	: "Being thrown",
	32	: "Stunned & Forced-OTG Stun",
	33	: "???",
	34	: "OC Launcher",
};