//Prox_Block Table
const ProxBlocKObj = 
{	
	0	:	"Neutral" ,
	1	:	"Air" ,
	2	:	"Dashing" ,
	3	:	"Crouching" ,
	4	:	"Turning Around" ,
	5	:	"Ground Block" ,
	6	:	"Air Block" ,
	7	:	"Standing Punches" ,
	8	:	"Standing Kicks" ,
	9	:	"Crouching Punches" ,
	10	:	"Crouching Kicks" ,
	11	:	"Air Punches" ,
	12	:	"Air Kicks" ,
	13	:	"Stunned" ,
	14	:	"???" ,
	15	:	"Throwing" ,
	16	:	"Being thrown" ,
	17	:	"Getting up from OTG (Invulnerable," ,
	18	:	"Match Start (Throw Invulnerable," ,
	19	:	"Win Pose" ,
	20	:	"Tag-in & OC Launcher" ,
	21	:	"Specials & Snapbacks" ,
	22	:	"Supers" ,
	23	:	"???" ,
	24	:	"Assist Related" ,
	25	:	"???" ,
	26	:	"Air Dash" ,
}